import java.time.LocalDate;
import java.time.LocalTime;

import br.senac.criancaemfoco.modelo.dao.agendamento.AgendamentoDAO;
import br.senac.criancaemfoco.modelo.dao.agendamento.AgendamentoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.contato.ContatoDAO;
import br.senac.criancaemfoco.modelo.dao.contato.ContatoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.endereco.EnderecoDAO;
import br.senac.criancaemfoco.modelo.dao.endereco.EnderecoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.estoque.EstoqueDAO;
import br.senac.criancaemfoco.modelo.dao.estoque.EstoqueDAOImpl;
import br.senac.criancaemfoco.modelo.dao.insumo.InsumoDAO;
import br.senac.criancaemfoco.modelo.dao.insumo.InsumoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.papel.PapelDAO;
import br.senac.criancaemfoco.modelo.dao.papel.PapelDAOImpl;
import br.senac.criancaemfoco.modelo.dao.pessoa.aluno.AlunoDAO;
import br.senac.criancaemfoco.modelo.dao.pessoa.aluno.AlunoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.enfermeiro.EnfermeiroDAO;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.enfermeiro.EnfermeiroDAOImpl;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.escola.EscolaDAO;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.escola.EscolaDAOImpl;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.responsavel.ResponsavelDAO;
import br.senac.criancaemfoco.modelo.dao.pessoa.usuario.responsavel.ResponsavelDAOImpl;
import br.senac.criancaemfoco.modelo.dao.procedimento.ProcedimentoDAO;
import br.senac.criancaemfoco.modelo.dao.procedimento.ProcedimentoDAOImpl;
import br.senac.criancaemfoco.modelo.dao.turma.TurmaDAO;
import br.senac.criancaemfoco.modelo.dao.turma.TurmaDAOImpl;
import br.senac.criancaemfoco.modelo.entidade.agendamento.Agendamento;
import br.senac.criancaemfoco.modelo.entidade.contato.Contato;
import br.senac.criancaemfoco.modelo.entidade.endereco.Endereco;
import br.senac.criancaemfoco.modelo.entidade.estoque.Estoque;
import br.senac.criancaemfoco.modelo.entidade.insumo.Insumo;
import br.senac.criancaemfoco.modelo.entidade.papel.Papel;
import br.senac.criancaemfoco.modelo.entidade.pessoa.aluno.Aluno;
import br.senac.criancaemfoco.modelo.entidade.pessoa.usuario.enfermeiro.Enfermeiro;
import br.senac.criancaemfoco.modelo.entidade.pessoa.usuario.escola.Escola;
import br.senac.criancaemfoco.modelo.entidade.pessoa.usuario.responsavel.Responsavel;
import br.senac.criancaemfoco.modelo.entidade.procedimento.Procedimento;
import br.senac.criancaemfoco.modelo.entidade.turma.Turma;
import br.senac.criancaemfoco.modelo.enumeracao.status.Status;

public class Main {
	public static void main(String[] args) {
		AgendamentoDAO agendamentoDao = new AgendamentoDAOImpl();
		ContatoDAO contatoDao = new ContatoDAOImpl();
		EnderecoDAO enderecoDao = new EnderecoDAOImpl();
		EstoqueDAO estoqueDao = new EstoqueDAOImpl();
		InsumoDAO insumoDao = new InsumoDAOImpl();
		PapelDAO papelDao = new PapelDAOImpl();
		AlunoDAO alunoDao = new AlunoDAOImpl();
		EnfermeiroDAO enfermeiroDao = new EnfermeiroDAOImpl();
		EscolaDAO escolaDao = new EscolaDAOImpl();
		ResponsavelDAO responsavelDao = new ResponsavelDAOImpl();
		ProcedimentoDAO procedimentoDao = new ProcedimentoDAOImpl();
		TurmaDAO turmaDao = new TurmaDAOImpl();

		Agendamento agendamento = new Agendamento();
		Contato contatoResponsavel = new Contato();
		Contato contatoEnfermeiro = new Contato();
		Contato contatoEscola = new Contato();
		Endereco enderecoResponsavel = new Endereco();
		Endereco enderecoEscola = new Endereco();
		Estoque estoque = new Estoque();
		Insumo insumo = new Insumo();
		Papel papel = new Papel();
		Aluno aluno = new Aluno();
		Enfermeiro enfermeiro = new Enfermeiro();
		Escola escola = new Escola();
		Responsavel responsavel = new Responsavel();
		Procedimento procedimento = new Procedimento();
		Turma turma = new Turma();

		papel.setNomePapel("usuario");
		contatoEscola.setNumCelular("40028922");
		contatoEnfermeiro.setNumCelular("12345678");
		contatoResponsavel.setNumCelular("50020187");
		enderecoResponsavel.setBairro("bairro");
		enderecoResponsavel.setCep(89420640);
		enderecoResponsavel.setCidade("cidade");
		enderecoResponsavel.setEstado("estado");
		enderecoResponsavel.setLogradouro("logradouro");
		enderecoResponsavel.setNumero((short) 47);
		enderecoResponsavel.setTipo("Casa");
		enderecoEscola.setBairro("bairro 2");
		enderecoEscola.setCep(89420640);
		enderecoEscola.setCidade("cidade");
		enderecoEscola.setEstado("estado");
		enderecoEscola.setLogradouro("rua");
		enderecoEscola.setNumero((short) 24);
		enderecoEscola.setTipo("Instituição");
		responsavel.setIdFiscal("10987654321");
		responsavel.setNomeId("Roberto");
		responsavel.setSobrenome("Gomes");
		responsavel.setEmail("responsavel@incrivel");
		responsavel.setSenha("123456789");
		responsavel.setDataNascimento(LocalDate.parse("1970-08-12"));
		aluno.setIdFiscal("12345678910");
		aluno.setNomeId("Nicolas");
		aluno.setSobrenome("Gomes");
		aluno.setDataNascimento(LocalDate.parse("2000-07-20"));
		aluno.setMatricula("67541");
		enfermeiro.setIdFiscal("91827346500");
		enfermeiro.setNomeId("Larissa");
		enfermeiro.setSobrenome("Silva");
		enfermeiro.setEmail("enfermeira@legal");
		enfermeiro.setSenha("987654321");
		enfermeiro.setDataNascimento(LocalDate.parse("1980-05-28"));
		enfermeiro.setRegistroCoren("123456");
		escola.setIdFiscal("01234567000189");
		escola.setNomeId("Escola Feliz");
		escola.setEmail("escola@feliz");
		escola.setSenha("198237465");
		turma.setAnoTurma((byte) 6);
		turma.setNumeroTurma("01");
		insumo.setNomeInsumo("Paracetamol");
		insumo.setDataValidade(LocalDate.parse("2024-12-08"));
		insumo.setDescricao("Capsula de Paracetamol");
		estoque.setQuantidade((byte) 20);
		procedimento.setNomeProcedimento("Tomar paracetamol");
		agendamento.setData(LocalDate.parse("2024-11-11"));
		agendamento.setHorario(LocalTime.parse("10:15:00"));
		agendamento.setStatus(Status.AGENDADO);
		agendamento.setTempoDuracao(LocalTime.parse("00:01:00"));

		papelDao.inserirPapel(papel);
		contatoDao.inserirContato(contatoEscola);
		contatoDao.inserirContato(contatoEnfermeiro);
		contatoDao.inserirContato(contatoResponsavel);
		enderecoDao.inserirEndereco(enderecoEscola);
		enderecoDao.inserirEndereco(enderecoResponsavel);
		
		escolaDao.inserirEscola(escola);
		responsavelDao.inserirResponsavel(responsavel);
		turmaDao.inserirTurma(turma);
		enfermeiroDao.inserirEnfermeiro(enfermeiro);
		alunoDao.inserirAluno(aluno);
		
		agendamentoDao.inserirAgendamento(agendamento);
		insumoDao.inserirInsumo(insumo);
		procedimentoDao.inserirProcedimento(procedimento);
		estoqueDao.inserirEstoque(estoque);

		procedimento.inserirInsumo(insumo);
		escola.inserirEstoque(estoque);
		escola.inserirProcedimento(procedimento);
		agendamento.inserirProcedimento(procedimento);
		agendamento.setEnfermeiro(enfermeiro);
		agendamento.setAluno(aluno);
		aluno.setTurma(turma);
		escola.inserirAluno(aluno);
		turma.setEscola(escola);
		responsavel.setPapel(papel);
		responsavel.setEndereco(enderecoResponsavel);
		responsavel.setContato(contatoResponsavel);
		aluno.setResponsavel(responsavel);
		responsavel.inserirDependente(aluno);
		enfermeiro.setPapel(papel);
		enfermeiro.setContato(contatoEnfermeiro);
		escola.setPapel(papel);
		escola.setContato(contatoEscola);
		escola.setEndereco(enderecoEscola);
		escola.inserirEnfermeiro(enfermeiro);
		turma.inserirAlunoTurma(aluno);
		turma.setEscola(escola);
		escola.inserirTurma(turma);
		estoque.setInsumo(insumo);

		papelDao.atualizarPapel(papel);
		contatoDao.atualizarContato(contatoEscola);
		contatoDao.atualizarContato(contatoEnfermeiro);
		contatoDao.atualizarContato(contatoResponsavel);
		enderecoDao.atualizarEndereco(enderecoEscola);
		enderecoDao.atualizarEndereco(enderecoResponsavel);

		escolaDao.atualizarEscola(escola);
		responsavelDao.atualizarResponsavel(responsavel);
		turmaDao.atualizarTurma(turma);
		enfermeiroDao.atualizarEnfermeiro(enfermeiro);
		alunoDao.atualizarAluno(aluno);

		agendamentoDao.atualizarAgendamento(agendamento);
		insumoDao.atualizarInsumo(insumo);
		procedimentoDao.atualizarProcedimento(procedimento);
		estoqueDao.atualizarEstoque(estoque);
	}
}
